# Generated by Django 2.2.4 on 2021-03-24 15:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0002_auto_20210323_2218'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MensagemContactos',
            new_name='Mensagens',
        ),
    ]
