# Generated by Django 2.2.4 on 2021-03-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20210324_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagens',
            name='lida',
            field=models.BooleanField(default=False),
        ),
    ]
