# Generated by Django 2.2.4 on 2021-03-25 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_mensagens_assunto'),
    ]

    operations = [
        migrations.AddField(
            model_name='enderecos',
            name='tel1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='enderecos',
            name='tel2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mensagens',
            name='assunto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Contactos',
        ),
    ]
