# Generated by Django 2.2.4 on 2021-03-26 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0011_auto_20210325_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='criadoPor',
        ),
        migrations.AddField(
            model_name='endereco',
            name='atualizadoPor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
