# Generated by Django 2.2.4 on 2021-03-26 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_auto_20210325_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sobre',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='sobre',
            name='subTitulo',
        ),
    ]
