# Generated by Django 2.2.4 on 2021-03-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_auto_20210326_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sobre',
            name='titulo',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
