# Generated by Django 2.2.4 on 2021-04-03 22:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_auto_20210326_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividadeslink',
            name='dataAtualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Data. Atualização'),
        ),
        migrations.AddField(
            model_name='actividadeslink',
            name='dataCriacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data. Criação'),
            preserve_default=False,
        ),
    ]
