# Generated by Django 2.2.4 on 2021-04-29 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0003_auto_20210429_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectos',
            name='estado',
            field=models.CharField(choices=[('1', 'Parado'), ('2', 'Concluído'), ('3', 'Em produção')], default='prado', max_length=100),
        ),
    ]
