# Generated by Django 2.2.4 on 2021-04-29 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0004_auto_20210429_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectos',
            name='projecto',
            field=models.FilePathField(allow_folders=True, blank=True),
        ),
    ]
