# Generated by Django 2.2.4 on 2021-04-30 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0006_auto_20210429_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectos',
            name='estado',
            field=models.CharField(choices=[('Parado', 'Parado'), ('Concluído', 'Concluído'), ('Em produção', 'Em produção')], default='prado', max_length=100),
        ),
    ]
