# Generated by Django 2.2.4 on 2021-04-30 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0007_auto_20210430_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectos',
            name='dataConclusao',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
