# Generated by Django 2.2.4 on 2021-04-30 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0008_auto_20210430_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectos',
            name='projecto',
            field=models.FileField(blank=True, default=None, null=True, upload_to='Projectos'),
        ),
    ]
