# Generated by Django 2.2.4 on 2021-03-25 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20210324_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensagens',
            name='criadoPor',
        ),
        migrations.RemoveField(
            model_name='mensagens',
            name='dataAtualizacao',
        ),
    ]
